### ISSUE TITLE
Tooltip checklist

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#11915]
It's really important that the user knows whats the purpose of all the icons/buttons in the action-heavy form is:

- [ ] When you hover over an `add` / `remove` button:  `Add X`, `Remove X `
- [ ] If an `add` / `remove` button is disabled: eg. `You must have at least one y-axis`
- [ ] When you hover over the agg type:`Aggregation type : count.` . If applicable add `Click to change` on the next line. 
- [ ] When you hover over sorting pill: `Sorted in ascending order. Click to reverse`
- [ ] When you hover over the 'align' segmented control : `Position: Right axis`
- [ ] When you hover over 'eye' icon: 'Click to hide'
---
- [ ] All tooltips should have a slight delay
- [ ] Tooltip should be the same style size as the tooltip used in the rest of the sql runner
<img width="61" alt="Screenshot 2024-10-14 at 11 03 53" src="https://github.com/user-attachments/assets/d99aa6ca-7445-4f14-82f8-8729cb4639a5">
