### ISSUE TITLE
Tooltips checklist

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#12247]
### Bug
<img width="1440" alt="Screenshot 2024-11-14 at 20 20 37" src="https://github.com/user-attachments/assets/3b2f7d97-0955-45ca-af22-69f2def654c1">
- [ ] Tooltips persist after sorting and kind of break the page!!! What can be done here?

### Copy

- [x] All these should have a slight delay that work with the transitions we decided (200 or 300, whatever we decided. yes this is a message from future pri)

- [x] Description Table Header (Text and icon):
"Defined in the metric's .yml file"

- [x] Category Table Header(Text and icon):
"Click to add or edit a category, if you have the required permissions."

- [x] Popularity Table Header (Text and icon):
"Shows how many charts use this metric."

- [x] All Categories Tag:
"Easily filter metrics by category to find what you're looking for."

- [x] Number of Charts Pill (Popularity Cell):
"Used by XX charts. Click to view the full list."

- [x] Explore Button:
"Open this metric in the explorer for detailed insights."

- [x] Search Bar Tooltip:
`Search by metric name or description'

--

### Size
- [x] All tooltips should be this size:
<img width="179" alt="Screenshot 2024-11-14 at 20 25 13" src="https://github.com/user-attachments/assets/4e7c672e-4ad5-4a34-ac76-703ef9b350fe">
