### ISSUE TITLE
I want the ability to add categories through the .yml files [CLOSE ME AT THE END OF MILESTONE]

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#12960]
- [ ] You’re able to optionally add ‘categories’ as a field in your .yml files per metric. 
- [ ] Once you refresh dbt, the categories will show up in the table. You cannot rename them or delete them off metrics.
- [ ] Colour : 
- [ ] - You can still add / delete / rename / change colour of categories in the UI. These remain ‘ ‘temporary’. 
- [ ] - For now, everything the .yml is in addition to the categories in the UI. 
- [ ] - Can you support table-wide categories?
