### ISSUE TITLE
Add api for tracking compiling jobs

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1874]
- [ ] Alter `POST /projects/{id}/refresh` to return a job id
- [ ] Alter frontend to store job id for polling 
- [ ] Replace `GET /projects/{id}/status` with `GET /jobs/{job_id}` and update frontend to use job id for polling
