### ISSUE TITLE
Show compile steps during onboarding

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1918]
**Tasks**

- [ ] Update the create project endpoint to be async - returning a job id (this should all happen in `ProjectService.create`
- [ ] Poll the job endpoint for job status and leaving the onboarding page in a spinning state
- [ ] Add callout showing steps returned from status endpoint (see design link)
- [ ] Job endpoint returns the created project uuid on success
- [ ] Redirect with project uuid on success

In onboarding, we think there are two things that need to be fixed about test + saving your connection:

1. Telling the user that a compile is happening 
2. Not having the compile as a long running http request that might completely fail

This ticket aims to fix 1.
https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=3396%3A76624&scaling=min-zoom&page-id=3396%3A76623&starting-point-node-id=3396%3A76624

### Schema

```
GET /jobs/{jobId}

200 {
  status: 'ok'
  results: {
    createdAt: ''
    updatedAt: ''
    jobStatus: 'DONE' | 'RUNNING' | 'ERROR',
    jobResults?: '/projects/{projectUuid}/explores'
    steps: [
      { 
       name: string,
       stepStatus: 'DONE' | 'RUNNING' | 'ERROR' | 'PENDING' | 'SKIPPED',
       error?: { name: string, message: string }
       startedAt: ''
       updatedAt: ''
     }
   ]
}
```

Steps  definition document: 

https://www.notion.so/lightdash/Refresh-dbt-2e15a707f1cf4d99b5d5f03c561eaebb#5cb13b94cb0342c09dfc33f36068f2ea

**Comment by rephus** [comment]
@TuringLovesDeathMetal @owlas I'm adding steps to just the /createProject endpoint, not to /refresh, I guess we need another ticket for that , with different steps .

**Comment by rephus** [comment]
Basically on https://github.com/lightdash/lightdash/pull/1925 I changed the endpoint to create the job and the steps, but I kept the endpoint async because we still need the Project to be returned on the frontend. Once we start working on this, we just need to make 2 small changes on the backend to make it fully async
