### ISSUE TITLE
Show Job steps when refreshing the schema

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#1952]
Related to  #1794

### Description: What is it?

We first updated the  /refresh that happens on Explore page, so it currently shows a nice popup . That frontend is done, but we are missing adding steps to that endpoint . Based on this UI design document https://www.notion.so/Refresh-dbt-2e15a707f1cf4d99b5d5f03c561eaebb#5cb13b94cb0342c09dfc33f36068f2ea

![image](https://user-images.githubusercontent.com/1983672/165968475-fce1325d-9338-43fa-ba4e-b9c90374e3cd.png)

### Tasks 

- [x] /refresh is returning a jobUuid , and doing the refresh asynchronously
- [x] Job and steps are returned on /job/{jobUuid} endpoint  
- [ ] Inside the /refresh async method, add the steps the backend 
- [ ] once that is done it should be easy to show the side panel with all steps

### Problem: What problem does this solve?

Tell the user what the refresh is doing

**Comment by owlas** [comment]
closing for #1918
