### ISSUE TITLE
Define abilities for project-level roles

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2437]
**Tasks**

- [x] Add new project abilities
- [ ] Update services to check new abilities

### Description

Create a new ability builder similar to `organizationMemberAbility` but for projects `projectMemberAbility`

This ability maps two inputs:

* role: viewer/editor/admin
* project uuid

to the following abilities **if** the project uuid of the subject matches the project-level role

| subject | action | viewer | editor | admin |
|---|---|---|---|---|
| Dashboard | view | x | x | x |
| Dashboard | manage | | x | x|
| SavedChart | view | x | x | x |
| SavedChart | manage | | x | x |
| Project | view | x | x | x |
| Project | manage | | | x |
| Job | manage | | x | x |

**Update service layer to check project level permissions**

* DashboardService
* OrganizationService
* ProjectService
* SavedChartsService
* UserService

### What problem does this solve?

Prepares for project level permissions

**Comment by rephus** [comment]
`Add new project abilities ` was done here https://github.com/lightdash/lightdash/pull/2446 but we are still missing: 

- [ ] Update services to check new abilities
