### ISSUE TITLE
State Tracking Features

### ISSUE THREAD

**Issue by silentninja** [lightdash/lightdash#405]
PR #388 adds dirty state change tracking, which enables us to show diff between the current query and the new query that is yet to run. Below is the list of features that should be possible:

- [ ]  Saved queries will save the local state/changes (ie) what you see. There should be an option to see what changes will be saved, to prevent saving unwanted changes. 
- [ ] Hide empty table columns. Sort might have to be pulled out of the table and be added like a filter.
- [ ] Show the list of active fields on that sidebar that were newly added or removed. https://www.loom.com/share/0caaa0f06c4443b1aa7b8458bcd3756a
- [ ] Show the diff between that last compiled Sql query and the one modified yet to run query.
- [ ] Show the changes to filters and sorts since last query.
- [ ] Prevent running the same query accidentally by changing the `Run Query` button to show only on state change. Force fetch option should be a drop-down to rerun the same query.

**Comment by silentninja** [comment]
This is more of a proposal/discussion, please move this to discussion forum if appropriate.

**Comment by silentninja** [comment]
Show the diff between that last compiled Sql query and the one modified yet to run query.
![localhost_3000_tables_payments_dimensions=orders_status metrics=payments_payment_count limit=500 column_order=payments_payment_count%2Corders_status (1)](https://user-images.githubusercontent.com/4469754/131859091-e7ae15be-7f06-44a5-97eb-beebf6fdda84.jpg)

**Comment by owlas** [comment]
Closing this as we haven't received interest in supporting this feature.
