### ISSUE TITLE
Styling updates to 'metrics as rows' pivot table

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#5029]
Suggestions to make some fields stand out more than others: 

<img width="1420" alt="Frame 5 (2)" src="https://github.com/lightdash/lightdash/assets/12776522/9f4a71c7-f733-42c9-8b9e-889df21c9863">

**how to differentiate between groups:**
- [x] Make the group headers colour black and font-weight:600. There can be more than one bold header #5740
- [x] Make the 'less-important fields' font-weight font-weight:400 #5740 

**how to make it obvious that the totals are totals**
- [x] #5771
- [ ] #5804
- [x] Total cells should have a light grey background or clear divider between them #5740 

**How to understand which labels apply to which group (options):** 

- [ ] some sort of arrow showing the direction
- [ ] interactivity. So hover over a label and the row/column will highlight. (maybe even metrics/dims)

@IrakliJani lets discuss what we can do here!
