### ISSUE TITLE
Add option to customize the format of a custom metric [Close me at the end of the milestone!]

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7344]
### Description

When I create a custom metric, there should be an option to customize the format. 

### Acceptance criteria

Miro sketch: https://miro.com/app/board/uXjVNdj6O-Q=/?moveToWidget=3458764565905990492&cot=14

Maybe we can use an accordion? https://v6.mantine.dev/core/accordion/#usage

- [ ] When you create a metric that is a numeric type, you have the option to `format` the custom metric while you're creating it. 
- [ ] This option is only available for numeric-type metrics
- [ ] The formatting options are the same as table calculations
- [ ] Let's remove the `optional` copy beside the filters tab while we're updating this modal. 
- [ ] To edit a custom metric's format, you just hit `edit custom metric` to reopen the modal
- [ ] Custom metrics with formatting applied appear in charts the same way that they appear in the results table
- [ ] Custom metrics with formatting applied appear in formatted .csv exports the same way that they appear in the results table. 

Engineering tasks: 
- [x] Create feature flag `custom-metrics-formatting` in Posthog
- [ ] Add new column to the `additional_metrics` table, which should mimic the same structure as the `table_calculations` one
- [ ] Add ability to create/edit a numeric Custom Metric with and without formatting: user can enable but also disable formatting when creating and editing
- [ ] Add another accordion to apply the formatting (below `filters`) if `numeric` type - hide that if not
