### ISSUE TITLE
[Close at the end the Milestone] Refactor app into a single `App` object

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#9099]
### Description

How can we export `LightdashApp` from @lightdash/backend and have it executable? Do we need a different entrypoint for running the backend (similar to `worker.ts`)? 

### Goal

Allow us to create a Lightdash App and provide all the necessary dependencies (routes/services/models/database/etc). 
It should be possible to extend/override any of those dependencies without making changes to those files.

### Subtasks:
- [x] https://github.com/lightdash/lightdash/issues/9147
- [x] https://github.com/lightdash/lightdash/issues/9149
- [x] https://github.com/lightdash/lightdash/issues/9151
- [x] https://github.com/lightdash/lightdash/issues/9155
- [x] #9163
- [x] #9173
- [x] #9174
- [x] #9178
- [x] #9216
- [x] #9218
- [x] #9247
